// Code generated by protoc-gen-gofullmethods. DO NOT EDIT.
// versions:
// - protoc-gen-gofullmethods v1.0.0
// - protoc                   v3.14.0
// source: helloworld

package example

const (
	Greeter_SayHello = "/helloworld.Greeter/SayHello"
	Greeter_SayBye   = "/helloworld.Greeter/SayBye"
)

var (
	FullMethods = []string{
		Greeter_SayHello,
		Greeter_SayBye,
	}
)
